name: QMake Build Matrix
on: [push, pull_request]

env:
  QT_VERSION: 5.15.1
  QT_CREATOR_VERSION: 4.13.2
  PLUGIN_PRO: cipher.pro
  PLUGIN_NAME: Cipher

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: windows-latest
    strategy:
      matrix:
        os: [windows-latest]
        version: ['5.15.1']

    steps:
    - name: Install Qt with options
      with:
        modules: 'widgets'
        version: ${{ matrix.version }}
    - name: Configure
      shell: qmake {0}
      run: |
        mingw32-make

    - uses: actions/upload-artifact@v2
      id: upload_artifact
      with:
        path: ./${{ env.PLUGIN_NAME }}-${{ env.QT_CREATOR_VERSION }}-${{ matrix.config.artifact }}
        name: ${{ env.PLUGIN_NAME}}-${{ env.QT_CREATOR_VERSION }}-${{ matrix.config.artifact }}
